### ISSUE TITLE
Support python 3.5

### ISSUE THREAD

**Issue by name3anad** [uncaughtxcptn/endpoints#43] opened 2018-02-13 12:12 UTC
The product is developed and tested on python 3.6. We need it to work with python 3.5 since it's the default python3 version in ec2.

**Comment by aldnav** [comment] 2018-02-13 13:35
@name3anad a stactrace would be helpful. Is it available?

**Comment by name3anad** [comment] 2018-02-13 13:52
Hi @aldnav . Thank you for dealing with this issue. Here is the log that I get when running the project inside an ec2 instance.
```
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    web.run_app(app, host='127.0.0.1', port=int(port))
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiohttp/web.py", line 442, in run_app
    loop.run_until_complete(app.startup())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiohttp/web.py", line 264, in startup
    yield from self.on_startup.send(self)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiohttp/signals.py", line 51, in send
    yield from self._send(*args, **kwargs)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiohttp/signals.py", line 17, in _send
    yield from res
  File "/home/ubuntu/endpoints/src/endpoints/db.py", line 91, in init_pg
    port=db_conf['port'])
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/utils.py", line 70, in __await__
    resp = yield from self._coro
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/sa/engine.py", line 70, in _create_engine
    pool_recycle=pool_recycle, **kwargs)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/utils.py", line 65, in __iter__
    resp = yield from self._coro
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/pool.py", line 47, in _create_pool
    yield from pool._fill_free_pool(False)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/pool.py", line 209, in _fill_free_pool
    **self._conn_kwargs)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/utils.py", line 65, in __iter__
    resp = yield from self._coro
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/connection.py", line 74, in _connect
    yield from conn._poll(waiter, timeout)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/connection.py", line 240, in _poll
    yield from asyncio.shield(cancel(), loop=self._loop)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/endpoints/env/lib/python3.5/site-packages/aiopg/connection.py", line 226, in cancel
    self._conn.cancel()
psycopg2.OperationalError: asynchronous connection attempt underway
```

**Comment by aldnav** [comment] 2018-02-13 15:47
@name3anad local buiild works fine
```
(endpoints-VltUX20A) ➜  endpoints git:(master) ✗ python main.py                
======== Running on http://127.0.0.1:8080 ========                             
(Press CTRL+C to quit)
^C%                                                                            
(endpoints-VltUX20A) ➜  endpoints git:(master) ✗ python --version              
Python 3.5.2
```

will check to see the specific error

**Comment by aldnav** [comment] 2018-02-13 16:51
@name3anad seems like this problem is related to database. Tried testing it on an RDS instance and can confirm that the issue is there. Will investigate more.

**Comment by aldnav** [comment] 2018-02-13 17:09
@name3anad I created an RDS instance and has now successfully connected. Can you try inspecting your RDS security group? Check to see the "Inbound" tab accepting requests from "Anywhere".

Although if this successfully connects to the rds instance, and the main server passes, I don't have a professional opinion about what rules to set for the security group. Maybe for testing, it's safer to add specific IPs.

**Comment by name3anad** [comment] 2018-02-13 17:46
@aldnav thank you for the input. You were right, it was because of the security groups settings of the RDS. I've updated to config and now its up and running. http://ec2-52-77-210-176.ap-southeast-1.compute.amazonaws.com Thank you

**Comment by aldnav** [comment] 2018-02-13 18:37
@name3anad I tried to run on an ec2 instance using the same rds setting I ran locally, it runs without errors.

```
(endpoints-GNXeTweN) [ec2-user@ip-ohyeaohyeah endpoints]$ python main.py --port=8000
======== Running on http://127.0.0.1:8000 ========
(Press CTRL+C to quit)


```

**Comment by aldnav** [comment] 2018-02-13 18:40
@name3anad Oh, I was so deep down the rabbit hole haven't even noticed your reply an hour ago. Sure! Welcome. Glad of help. :+1:

**Comment by arnellebalane** [comment] 2018-02-15 16:49
I believe this issue is now resolved, right? @name3anad @aldnav

**Comment by aldnav** [comment] 2018-02-15 16:52
@arnellebalane issue is now resolved. Closing.

**Closed by aldnav** 2018-02-15 16:52 UTC
Labels: bug
